apiVersion: apps/v1
kind: Deployment
metadata:
  name: inli-deployment
  namespace: inli-ns
spec:
  template:
    spec:
      containers:
      - name: inli-pod
        envFrom:
        - configMapRef:
            name: inli-config-map-ile-de-france
        - secretRef:
            name: inli-secret-ile-de-france
