apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -ile-de-france

resources:
  - ../../base

labels:
  - pairs:
      place: inli-ile-de-france

patches:
  - path: ConfigMap-ile-de-france.yaml
  - path: Deployment-ile-de-france.yaml
  