apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: portfolio-ns
  labels:
    app: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolio-pod
        image: elhaddaoui/hamzaportfolio:94f437a84b0f7b5fad420cd5f8f5722e8cf8ba45
        imagePullPolicy: IfNotPresent
      nodeSelector:
        node: home-applications