apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inli-pvc
  namespace: inli-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi