apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inli-pvc
  namespace: inli-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi